version: "3"
services:
  # docker run --rm -it --device /dev/snd --security-opt seccomp=unconfined -p 3000:3000 zeeshans/slim:prayer-alarm-rust
  prayer-alarm:
    image: zeeshans/slim:prayer-alarm-rust
    # build:
    #   context: .
    #   dockerfile: rpi.Dockerfile
    container_name: prayer-alarm
    restart: unless-stopped
    devices:
      - /dev/snd
    security_opt:
      - seccomp=unconfined
    ports:
      - "3000:3000"
